### ISSUE TITLE
Some suggestions to the library...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [DWorkS/AStickyHeader#5]
I have some suggestions and remarks of how to improve the code of the library.

Here are things i've modified to the code and added a link to download:
1. many of the files on the library itself aren't needed or doesn't belong to it, and many aren't even used.
   in fact, no resource is really needed by the library.
2. the jar file of the support library isn't needed here, as it's already provided in ABS. This can (and will) cause compilation errors when using newer versions of the support library (or of ABS).
3. there are many Lint warnings about too-new APIs. I really hope they are false positives. I've already tested the sample project and it works fine on Android 2.3 .
   There are also other less-important warnings (like un-needed check of null, double ";" characters,...) . 
4. The color resource "white" wasn't found anywhere. It should either be declared or something else should be used (like 
   "@android:color/white" instead of "@color/white" ) .

Here are things I think should be added:
1. the SimpleSectionedGridAdapter is too hard to customize, especially the header part. it could be nice to be able to have an abstract function called "handleHeaderView" instead of using a layout resource Id and an id of the textview within it.
2. there is no usage of the ViewHolder design pattern (watch "the world of listView" lecture for more information). this could make a smoother experience.
3. HeaderLayout isn't really needed. you can change the layout of whatever view that was used there, and update it, for example:
   
   ```
   layoutParams = header.getLayoutParams();
   layoutParams.width = getHeaderSize();
   header.setLayoutParams(layoutParams);
   ```

For some reason I can't find out how to upload files here, so I've uploaded to a third party website (google drive). Here is a minimized version of the projects:
https://drive.google.com/file/d/0B_nrUhQ0MIgwdFRaNnNVR3QycDA/edit?usp=sharing

Please let me know what you think about it.
